export let startValue = 100;

export let products = [
  {
    name: "Колбаса п/к Застольная б/с",
    id: 1,
    outputValue: 95.0,
    ingredientsPrimary: [
      { nameIngredient: "мясо говяжьих голов", amount: 52.0 },
      { nameIngredient: "шпик", amount: 20.0 },
      { nameIngredient: "изолят соевого белка", amount: 7.0 },
      { nameIngredient: "вода", amount: 21.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 0.7 },
      { nameIngredient: "пнс", amount: 1.6 },
      { nameIngredient: "биями комби 37", amount: 1.7 },
      { nameIngredient: "донор 16", amount: 0.2 },
      { nameIngredient: "чесночный порошок", amount: 0.1 },
      { nameIngredient: "черева говяжья", amount: 9.1 },
      { nameIngredient: "шпагат", amount: 0.238 },
    ],
  },
  {
    name: "Шашлык Южный в маринаде",
    id: 2,
    outputValue: 140.0,
    ingredientsPrimary: [{ nameIngredient: "свинина нежирная", amount: 100.0 }],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 0.8 },
      { nameIngredient: "про ветчина 30А", amount: 1.2 },
      { nameIngredient: "растительное масло", amount: 7.0 },
      { nameIngredient: "маринад пирожка", amount: 3.0 },
      { nameIngredient: "пакет большой", amount: 28 },
    ],
  },
  {
    name: "Колбаса п/к Фермерская с грибочками и лучком в/с",
    id: 3,
    outputValue: 110.0,
    ingredientsPrimary: [
      { nameIngredient: "свинина полужирная", amount: 75.0 },
      { nameIngredient: "говядина односортная", amount: 20.0 },
      { nameIngredient: "крахмал", amount: 5.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "пнс", amount: 1.2 },
      { nameIngredient: " совмикс Ф500", amount: 1.5 },
      { nameIngredient: "соваром грибной", amount: 1.35 },
      { nameIngredient: "комбивит", amount: 0.4 },
      { nameIngredient: "совицель", amount: 0.3 },
      { nameIngredient: "черева говяжья", amount: 10.6 },
      { nameIngredient: "шпагат", amount: 0.275 },
      { nameIngredient: "пакет вакуумный", amount: 275 },
      { nameIngredient: "соваром цебуля", amount: 0.3 },
    ],
  },
  {
    name: "Колбаса п/к Тминная 1с",
    id: 4,
    outputValue: 100.0,
    ingredientsPrimary: [
      { nameIngredient: "свинина полужирная", amount: 46.0 },
      { nameIngredient: "шпик", amount: 12.0 },
      { nameIngredient: "говядина 2 сорта", amount: 10.0 },
      { nameIngredient: "мясо говяжьих голов", amount: 30.0 },
      { nameIngredient: "мука 1 сорт", amount: 2.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 1.4 },
      { nameIngredient: "пнс", amount: 1.0 },
      { nameIngredient: "тарома микс примо", amount: 1.0 },
      { nameIngredient: "тмин", amount: 0.3 },
      { nameIngredient: "черева говяжья", amount: 9.6 },
      { nameIngredient: "шпагат", amount: 0.25 },
      { nameIngredient: "пакет вакуумный", amount: 50 },
    ],
  },
  {
    name: "Колбаса п/к Шашлычная 1с",
    id: 5,
    outputValue: 100.0,
    ingredientsPrimary: [
      { nameIngredient: "свинина полужирная", amount: 40.0 },
      { nameIngredient: "говядина 2 сорта", amount: 25.0 },
      { nameIngredient: "мясо говяжьих голов", amount: 15.0 },
      { nameIngredient: "шпик", amount: 17.0 },
      { nameIngredient: "крахмал", amount: 2.0 },
      { nameIngredient: "сухое молоко", amount: 1.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 1.1 },
      { nameIngredient: "пнс", amount: 1.0 },
      { nameIngredient: "сервелат домашний", amount: 1.2 },
      { nameIngredient: "тарома стаб 11", amount: 1.0 },
      { nameIngredient: "черева свиная", amount: 16.9 },
      { nameIngredient: "шпагат", amount: 0.25 },
      { nameIngredient: "пакет вакуумный", amount: 50 },
    ],
  },
  {
    name: "Сервелат в/к Рублевский в/с",
    id: 6,
    outputValue: 100.0,
    ingredientsPrimary: [
      { nameIngredient: "свинина полужирная", amount: 40.0 },
      { nameIngredient: "говядина односортная", amount: 40.0 },
      { nameIngredient: "шпик", amount: 20.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "пнс", amount: 1.8 },
      { nameIngredient: "соваром из под стехи", amount: 1.0 },
      { nameIngredient: "кутроцит", amount: 0.8 },
      { nameIngredient: "комбивит", amount: 0.4 },
      { nameIngredient: "каркадогель", amount: 0.1 },
      { nameIngredient: "фиброуз д55", amount: 70.0 },
      { nameIngredient: "скрепки", amount: 376 },
      { nameIngredient: "петли", amount: 188 },
      { nameIngredient: "пакет вакуумный", amount: 333 },
    ],
  },
  {
    name: "Сервелат в/к Бременский в/с",
    id: 7,
    outputValue: 100.0,
    ingredientsPrimary: [
      { nameIngredient: "говядина односортная", amount: 35.0 },
      { nameIngredient: "шпик", amount: 25.0 },
      { nameIngredient: "свинина полужирная", amount: 20.0 },
      { nameIngredient: "мясо говяжьих голов", amount: 20.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "пнс", amount: 1.8 },
      { nameIngredient: "соваром салями", amount: 1.1 },
      { nameIngredient: "кутроцит", amount: 0.8 },
      { nameIngredient: "комбивит", amount: 0.4 },
      { nameIngredient: "каркадогель", amount: 0.15 },
      { nameIngredient: "фиброуз д55", amount: 70.0 },
      { nameIngredient: "скрепки", amount: 376 },
      { nameIngredient: "петли", amount: 188 },
      { nameIngredient: "пакет вакуумный", amount: 333 },
    ],
  },
  {
    name: "Сервелат в/к Ореховый в/с",
    id: 8,
    outputValue: 100.0,
    ingredientsPrimary: [
      { nameIngredient: "свинина полужирная", amount: 35.5 },
      { nameIngredient: "говядина односортная", amount: 34.0 },
      { nameIngredient: "шпик", amount: 15.0 },
      { nameIngredient: "мясо говяжьих голов", amount: 15.0 },
      { nameIngredient: "грецкий орех", amount: 0.5 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "пнс", amount: 1.8 },
      { nameIngredient: "соваром орехи", amount: 0.83 },
      { nameIngredient: "кутроцит", amount: 0.8 },
      { nameIngredient: "комбивит", amount: 0.4 },
      { nameIngredient: "каркадогель", amount: 0.2 },
      { nameIngredient: "фиброуз д55", amount: 70 },
      { nameIngredient: "скрепки", amount: 376 },
      { nameIngredient: "петли", amount: 188 },
      { nameIngredient: "пакет вакуумный", amount: 333 },
    ],
  },
  {
    name: "Колбаса п/к Крестьянская в/с",
    id: 9,
    outputValue: 110.0,
    ingredientsPrimary: [
      { nameIngredient: "мясо говяжьих голов", amount: 40.0 },
      { nameIngredient: "свинина жирная", amount: 25.0 },
      { nameIngredient: "свинина полужирная", amount: 20.0 },
      { nameIngredient: "шкурка свиная", amount: 15.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "пнс", amount: 1.8 },
      { nameIngredient: " совмикс Ф500", amount: 1.4 },
      { nameIngredient: "соваром чоризо", amount: 1.1 },
      { nameIngredient: "комбивит", amount: 0.4 },
      { nameIngredient: "совицель", amount: 0.4 },
      { nameIngredient: "черева свиная", amount: 18.6 },
      { nameIngredient: "шпагат", amount: 0.275 },
      { nameIngredient: "пакет вакуумный", amount: 138 },
    ],
  },
  {
    name: "Колбаса п/к Чабай по-венгерски в/с",
    id: 10,
    outputValue: 110.0,
    ingredientsPrimary: [
      { nameIngredient: "свинина полужирная", amount: 75.0 },
      { nameIngredient: "свинина жирная", amount: 20.0 },
      { nameIngredient: "крахмал", amount: 5.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "пнс", amount: 1.8 },
      { nameIngredient: " совмикс Ф500", amount: 1.5 },
      { nameIngredient: "соваром телячья", amount: 0.8 },
      { nameIngredient: "комбивит", amount: 0.4 },
      { nameIngredient: "совицель", amount: 0.3 },
      { nameIngredient: "черева свиная", amount: 18.6 },
      { nameIngredient: "шпагат", amount: 0.275 },
      { nameIngredient: "пакет вакуумный", amount: 367 },
      { nameIngredient: "чесночный порошок", amount: 0.3 },
      { nameIngredient: "соваром бекон", amount: 0.15 },
      { nameIngredient: "колор плюс TRD", amount: 0.5 },
      { nameIngredient: "соваром де капрезе", amount: 0.8 },
    ],
  },
  {
    name: "Колбаса п/к Братвуртс в/с",
    id: 11,
    outputValue: 110.0,
    ingredientsPrimary: [
      { nameIngredient: "свинина полужирная", amount: 75.0 },
      { nameIngredient: "свинина жирная", amount: 20.0 },
      { nameIngredient: "крахмал", amount: 5.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "пнс", amount: 1.8 },
      { nameIngredient: " совмикс Ф500", amount: 1.5 },
      { nameIngredient: "соваром братвурст", amount: 1.0 },
      { nameIngredient: "комбивит", amount: 0.4 },
      { nameIngredient: "совицель", amount: 0.3 },
      { nameIngredient: "черева свиная", amount: 18.6 },
      { nameIngredient: "шпагат", amount: 0.275 },
      { nameIngredient: "пакет вакуумный", amount: 367 },
    ],
  },
  {
    name: "Колбаски в/к Охотничьи байки в/с",
    id: 12,
    outputValue: 100.0,
    ingredientsPrimary: [
      { nameIngredient: "м/о говяжья жилованная", amount: 40.0 },
      { nameIngredient: "свинина полужирная", amount: 40.0 },
      { nameIngredient: "мясо птицы кусковое", amount: 20.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "пнс", amount: 1.5 },
      { nameIngredient: " совмикс Ф500", amount: 1.0 },
      { nameIngredient: "соваром чоризо", amount: 1.0 },
      { nameIngredient: "комбивит", amount: 0.4 },
      { nameIngredient: "совицель", amount: 0.3 },
      { nameIngredient: "натурин д20", amount: 477.0 },
      { nameIngredient: "пакет вакуумный", amount: 200 },
    ],
  },
  {
    name: 'Фарш "По-деревенски"',
    id: 13,
    outputValue: 118.0,
    ingredientsPrimary: [
      { nameIngredient: "мясо свиных голов", amount: 100.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 0.8 },
      { nameIngredient: "картофельная клетчатка", amount: 2.0 },
      { nameIngredient: "бомбаль", amount: 0.5 },
      { nameIngredient: "пакет большой", amount: 24 },
    ],
  },
  {
    name: "Стейк из рульки",
    id: 14,
    outputValue: 104.0,
    ingredientsPrimary: [{ nameIngredient: "рулька 47/19/34", amount: 100.0 }],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 0.9 },
      { nameIngredient: "ирландское пиво", amount: 1.2 },
      { nameIngredient: "инъекта", amount: 0.75 },
      { nameIngredient: "бактицид", amount: 0.15 },
      { nameIngredient: "пакет большой", amount: 20 },
    ],
  },
  {
    name: "Ребро в маринаде",
    id: 15,
    outputValue: 104.0,
    ingredientsPrimary: [
      {
        nameIngredient: "грудореберная часть свиная с ребрами 50/50",
        amount: 100.0,
      },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 0.9 },
      { nameIngredient: "маринад Деревенский", amount: 4.0 },
      { nameIngredient: "инъекта", amount: 0.75 },
      { nameIngredient: "бактицид", amount: 0.15 },
      { nameIngredient: "пакет большой", amount: 10 },
    ],
  },
  {
    name: "Сосиски вареные Русские особые в/с",
    id: 16,
    outputValue: 137.0,
    ingredientsPrimary: [
      { nameIngredient: "говядина высшего сорта", amount: 30.0 },
      { nameIngredient: "говядина 1 сорта", amount: 20.0 },
      { nameIngredient: "свинина полужирная", amount: 30.0 },
      { nameIngredient: "свинина жирная", amount: 13.0 },
      { nameIngredient: "сухое молоко", amount: 5.0 },
      { nameIngredient: "меланж яичный сухой", amount: 0.548 },
      { nameIngredient: "вода", amount: 1.452 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 1.2 },
      { nameIngredient: "пнс", amount: 1.2 },
      { nameIngredient: "биямикс докторская", amount: 2.0 },
      { nameIngredient: "мусалонг", amount: 0.5 },
      { nameIngredient: "амипак д24", amount: 342.5 },
    ],
  },
  {
    name: "Продукт к/в Столичный новый",
    id: 17,
    outputValue: 80.0,
    ingredientsPrimary: [
      {
        nameIngredient: "шейная, позвоночная часть свиная 15/85",
        amount: 100.0,
      },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 0.4 },
      { nameIngredient: "пнс", amount: 2.0 },
      { nameIngredient: "хам брайн", amount: 2.25 },
      { nameIngredient: "актив фреш", amount: 0.5 },
      { nameIngredient: "пакет большой", amount: 8 },
    ],
  },
  {
    name: "Ноги свиные Аппетитные",
    id: 18,
    outputValue: 90.0,
    ingredientsPrimary: [
      { nameIngredient: "ноги свиные вареные", amount: 100.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 0.8 },
      { nameIngredient: "маринад BBQ", amount: 4.0 },
      { nameIngredient: "бактицид", amount: 0.3 },
      { nameIngredient: "пакет большой", amount: 9 },
    ],
  },
  {
    name: "Колбаса в/к Польская 1с.",
    id: 19,
    outputValue: 94.0,
    ingredientsPrimary: [
      { nameIngredient: "говядина 1 сорта", amount: 45.0 },
      { nameIngredient: "говядина 2 сорта", amount: 25.0 },
      { nameIngredient: "шпик", amount: 30.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 1.4 },
      { nameIngredient: "пнс", amount: 1.4 },
      { nameIngredient: "ветчинная краковская комби", amount: 0.9 },
      { nameIngredient: "фиброуз д45", amount: 99.3 },
      { nameIngredient: "скрепки", amount: 419 },
      { nameIngredient: "петли", amount: 210 },
    ],
  },
  {
    name: "Колбаса вареная Духмяная 2с.",
    id: 20,
    outputValue: 137.0,
    ingredientsPrimary: [
      { nameIngredient: "говядина 2 сорта", amount: 65.0 },
      { nameIngredient: "шпик", amount: 25.0 },
      { nameIngredient: "жир-сырец говяжий", amount: 5.0 },
      { nameIngredient: "сухое молоко", amount: 5.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 1.2 },
      { nameIngredient: "пнс", amount: 1.3 },
      { nameIngredient: "биямикс докторская", amount: 2.5 },
      { nameIngredient: "бига д.65", amount: 58.4 },
      { nameIngredient: "скрепки", amount: 1096 },
      { nameIngredient: "петли", amount: 548 },
    ],
  },
  {
    name: "Колбаса вареная Русская особая в/с.",
    id: 21,
    outputValue: 137.0,
    ingredientsPrimary: [
      { nameIngredient: "говядина высшего сорта", amount: 30.0 },
      { nameIngredient: "говядина 1 сорта", amount: 20.0 },
      { nameIngredient: "свинина полужирная", amount: 30.0 },
      { nameIngredient: "свинина жирная", amount: 13.0 },
      { nameIngredient: "сухое молоко", amount: 5.0 },
      { nameIngredient: "меланж яичный сухой", amount: 0.548 },
      { nameIngredient: "вода", amount: 1.452 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 1.2 },
      { nameIngredient: "пнс", amount: 1.2 },
      { nameIngredient: "биямикс докторская", amount: 2.0 },
      { nameIngredient: "мусалонг", amount: 0.5 },
      { nameIngredient: "бига д.65", amount: 58.4 },
      { nameIngredient: "скрепки", amount: 1096 },
      { nameIngredient: "петли", amount: 548 },
    ],
  },
  {
    name: "Колбаса с/к От бабушки в/с",
    id: 22,
    outputValue: 70.0,
    ingredientsPrimary: [
      { nameIngredient: "свинина полужирная", amount: 100.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 0.5 },
      { nameIngredient: "пнс", amount: 2.0 },
      { nameIngredient: "арома традиционная", amount: 0.8 },
      { nameIngredient: "арома классик", amount: 0.6 },
      { nameIngredient: "тарома гдл", amount: 1.0 },
      { nameIngredient: "черева свиная", amount: 13.2 },
      { nameIngredient: "шпагат", amount: 0.21 },
      { nameIngredient: "пакет вакуумный", amount: 233 },
    ],
  },
  {
    name: "Колбаса с/к Карпатская в/с",
    id: 23,
    outputValue: 70.0,
    ingredientsPrimary: [
      { nameIngredient: "свинина полужирная", amount: 100.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 0.8 },
      { nameIngredient: "пнс", amount: 2.0 },
      { nameIngredient: "салями пармская", amount: 1.0 },
      { nameIngredient: "комплекс гдл", amount: 1.0 },
      { nameIngredient: "черева свиная", amount: 13.2 },
      { nameIngredient: "шпагат", amount: 0.21 },
      { nameIngredient: "пакет вакуумный", amount: 280 },
    ],
  },
  {
    name: "Колбаса с/к Медовая в/с",
    id: 24,
    outputValue: 70.0,
    ingredientsPrimary: [
      { nameIngredient: "свинина полужирная", amount: 100.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 0.8 },
      { nameIngredient: "пнс", amount: 2.0 },
      { nameIngredient: "салями медовая", amount: 1.3 },
      { nameIngredient: "комплекс гдл", amount: 1.0 },
      { nameIngredient: "черева свиная", amount: 13.2 },
      { nameIngredient: "шпагат", amount: 0.21 },
      { nameIngredient: "пакет вакуумный", amount: 280 },
    ],
  },
  {
    name: 'Смалец соленый "Закусочный"',
    id: 25,
    outputValue: 98.0,
    ingredientsPrimary: [
      { nameIngredient: "шпик", amount: 50.0 },
      { nameIngredient: "жир-сырец свиной", amount: 30.0 },
      { nameIngredient: "свинина полужирная", amount: 20.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 3.0 },
      { nameIngredient: "про смак", amount: 1.5 },
      { nameIngredient: "пряно-аром. приправа Домашняя", amount: 1.0 },
      { nameIngredient: "фиброуз д45", amount: 88.2 },
      { nameIngredient: "скрепки", amount: 549 },
      { nameIngredient: "петли", amount: 274 },
      { nameIngredient: "чесночный порошок", amount: 0.133 },
    ],
  },
  {
    name: 'Смалец соленый "По-домашнему"',
    id: 26,
    outputValue: 104.0,
    ingredientsPrimary: [
      { nameIngredient: "шпик", amount: 70.0 },
      { nameIngredient: "жир-сырец свиной", amount: 30.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 2.5 },
      { nameIngredient: "приправа Деревенская", amount: 1.3 },
      { nameIngredient: "чесночный порошок", amount: 0.3 },
      { nameIngredient: "фиброуз д45", amount: 93.6 },
      { nameIngredient: "скрепки", amount: 582 },
      { nameIngredient: "петли", amount: 291 },
    ],
  },
  {
    name: 'Купаты сырые "Сельские"',
    id: 27,
    outputValue: 105.0,
    ingredientsPrimary: [
      { nameIngredient: "свинина полужирная", amount: 70.0 },
      { nameIngredient: "жир-сырец свиной", amount: 15.0 },
      { nameIngredient: "изолят соевого белка", amount: 3.0 },
      { nameIngredient: "вода", amount: 12.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 2.0 },
      { nameIngredient: "приправа Деревенская", amount: 0.8 },
      { nameIngredient: "бактицид", amount: 0.3 },
      { nameIngredient: "черева свиная", amount: 15.2 },
      { nameIngredient: "тарелка лоток", amount: 105 },
    ],
  },
  {
    name: 'Колбаски сырые "Домашние"',
    id: 28,
    outputValue: 115.0,
    ingredientsPrimary: [
      { nameIngredient: "свинина полужирная", amount: 100.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 2.0 },
      { nameIngredient: "приправа Деревенская", amount: 0.8 },
      { nameIngredient: "бактицид", amount: 0.3 },
      { nameIngredient: "черева свиная", amount: 16.7 },
      { nameIngredient: "тарелка лоток", amount: 115 },
    ],
  },
  {
    name: 'Грудинка соленая "Для Гурмана"',
    id: 29,
    outputValue: 100.0,
    ingredientsPrimary: [
      { nameIngredient: "грудореберная часть свиная без ребер", amount: 100.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 8.0 },
      { nameIngredient: "приправа Русская", amount: 2.0 },
    ],
  },
  {
    name: 'Грудинка соленая "Дачная"',
    id: 30,
    outputValue: 100.0,
    ingredientsPrimary: [
      { nameIngredient: "грудореберная часть свиная без ребер", amount: 100.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 8.0 },
      { nameIngredient: "приправа Ароматная", amount: 2.0 },
    ],
  },
  {
    name: 'Грудинка соленая "Украинская"',
    id: 31,
    outputValue: 100.0,
    ingredientsPrimary: [
      { nameIngredient: "грудореберная часть свиная без ребер", amount: 100.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 8.0 },
      { nameIngredient: "приправа Праздничная", amount: 2.0 },
    ],
  },
  {
    name: 'Ветчина вареная "Слойка Любительская"',
    id: 32,
    outputValue: 95.0,
    ingredientsPrimary: [
      { nameIngredient: "шпик", amount: 20.0 },
      { nameIngredient: "печень", amount: 60.0 },
      { nameIngredient: "шкурка свиная вареная", amount: 20.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 2.0 },
      { nameIngredient: "тарома комби 3", amount: 0.7 },
      { nameIngredient: "проаром декор", amount: 0.5 },
      { nameIngredient: "чесночный порошок", amount: 0.017 },
      { nameIngredient: "пакет вакуумный", amount: 317 },
    ],
  },
  {
    name: 'Ветчина вареная "Пикантная"',
    id: 33,
    outputValue: 100.0,
    ingredientsPrimary: [
      { nameIngredient: "свинина полужирная", amount: 60.0 },
      { nameIngredient: "шкурка свиная вареная", amount: 40.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 1.0 },
      { nameIngredient: "пнс", amount: 1.0 },
      { nameIngredient: "тарома комби 3", amount: 1.0 },
      { nameIngredient: "перец черный молотый", amount: 0.6 },
      { nameIngredient: "лист лавровый", amount: 0.2 },
      { nameIngredient: "чесночный порошок", amount: 0.1 },
      { nameIngredient: "пакет вакуумный", amount: 333 },
    ],
  },
  {
    name: 'Ветчина вареная "Медвежье ухо"',
    id: 34,
    outputValue: 110.0,
    ingredientsPrimary: [
      { nameIngredient: "язык свиной вареный", amount: 60.0 },
      { nameIngredient: "уши свиные вареные", amount: 40.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 2.0 },
      { nameIngredient: "кориандр молотый", amount: 0.2 },
      { nameIngredient: "перец черный молотый", amount: 0.15 },
      { nameIngredient: "чесночный порошок", amount: 0.13 },
      { nameIngredient: "пакет вакуумный", amount: 367 },
    ],
  },
  {
    name: "Полендвица Деревенская",
    id: 35,
    outputValue: 85.0,
    ingredientsPrimary: [{ nameIngredient: "свинина нежирная", amount: 100.0 }],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 1.7 },
      { nameIngredient: "пнс", amount: 1.6 },
      { nameIngredient: "аромат полендвицы сырой", amount: 1.5 },
      { nameIngredient: "пакет вакуумный", amount: 170 },
    ],
  },
  {
    name: 'Соленый продукт из свинины "Солонина-полендвица"',
    id: 36,
    outputValue: 90.0,
    ingredientsPrimary: [{ nameIngredient: "свинина нежирная", amount: 100.0 }],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 5.0 },
      { nameIngredient: "про смак", amount: 1.5 },
      { nameIngredient: "пряно-аром. приправа Домашняя", amount: 1.5 },
      { nameIngredient: "пакет вакуумный", amount: 180 },
    ],
  },
  {
    name: 'Соленый продукт "Говядина Смачная"',
    id: 37,
    outputValue: 90.0,
    ingredientsPrimary: [
      { nameIngredient: "говядина высшего сорта", amount: 100.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 5.5 },
      { nameIngredient: "про смак", amount: 1.5 },
      { nameIngredient: "карри гриль", amount: 1.2 },
      { nameIngredient: "пакет вакуумный", amount: 180 },
    ],
  },
  {
    name: "Смалец соленый по-белорусски",
    id: 38,
    outputValue: 98.0,
    ingredientsPrimary: [{ nameIngredient: "свинина полужирная", amount: 100.0 }],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 3.0 },
      { nameIngredient: "про смак", amount: 1.5 },
      { nameIngredient: "приправа Барбекю обсыпка декор", amount: 1.0 },
      { nameIngredient: "чесночный порошок", amount: 0.135 },
      { nameIngredient: "контейнер 0,28л", amount: 350 },
    ],
  },
  {
    name: "Смалец соленый Русский",
    id: 39,
    outputValue: 98.0,
    ingredientsPrimary: [
      { nameIngredient: "свинина полужирная", amount: 100.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 3.0 },
      { nameIngredient: "про смак", amount: 1.5 },
      { nameIngredient: "карри гриль", amount: 1.0 },
      { nameIngredient: "чесночный порошок", amount: 0.135 },
      { nameIngredient: "контейнер 0,28л", amount: 350 },
    ],
  },
  {
    name: 'Фарш "Домашний любимый"',
    id: 40,
    outputValue: 105.0,
    ingredientsPrimary: [
      { nameIngredient: "мясо свиных голов", amount: 15.0 },
      { nameIngredient: "говядина 2 сорта", amount: 55.0 },
      { nameIngredient: "жир-сырец говяжий", amount: 30.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 1.5 },
      { nameIngredient: "премикс 26", amount: 0.3 },
      { nameIngredient: "мит фреш", amount: 0.3 },
      { nameIngredient: "пакет малый", amount: 105 },
    ],
  },
  {
    name: 'Фарш "Березовский"',
    id: 41,
    outputValue: 100.0,
    ingredientsPrimary: [
      { nameIngredient: "свинина полужирная", amount: 100.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "бактицид", amount: 0.5 },
      { nameIngredient: "пакет большой", amount: 33 },
      { nameIngredient: "пакет малый", amount: 50 },
    ],
  },
  {
    name: 'Фарш "Русский новый"',
    id: 42,
    outputValue: 100.0,
    ingredientsPrimary: [{ nameIngredient: "говядина 2 сорта", amount: 100.0 }],
    ingredientsSecondary: [
      { nameIngredient: "бактицид", amount: 0.5 },
      { nameIngredient: "пакет большой", amount: 33 },
    ],
  },
  {
    name: 'Колбаса сырая "С печенью"',
    id: 43,
    outputValue: 100.0,
    ingredientsPrimary: [
      { nameIngredient: "говядина 2 сорта", amount: 25.0 },
      { nameIngredient: "шпик", amount: 20.0 },
      { nameIngredient: "жир-сырец говяжий", amount: 7.0 },
      { nameIngredient: "печень", amount: 30.0 },
      { nameIngredient: "картофельная клетчатка", amount: 2.0 },
      { nameIngredient: "вода", amount: 16.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 1.2 },
      { nameIngredient: "донор 16", amount: 0.3 },
      { nameIngredient: "перец черный молотый", amount: 0.15 },
      { nameIngredient: "кориандр молотый", amount: 0.1 },
      { nameIngredient: "чесночный порошок", amount: 0.133 },
      { nameIngredient: "бомбаль", amount: 0.5 },
      { nameIngredient: "черева свиная", amount: 14.5 },
      { nameIngredient: "пакет большой", amount: 25 },
    ],
  },
  {
    name: 'Колбаса сырая "От бабушки"',
    id: 44,
    outputValue: 115.0,
    ingredientsPrimary: [
      { nameIngredient: "свинина нежирная", amount: 10.0 },
      { nameIngredient: "свинина полужирная", amount: 70.0 },
      { nameIngredient: "свинина жирная", amount: 20.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 1.6 },
      { nameIngredient: "чеснок гранулированный", amount: 0.45 },
      { nameIngredient: "кориандр горошек", amount: 0.7 },
      { nameIngredient: "семена горчицы", amount: 0.5 },
      { nameIngredient: "кориандр молотый", amount: 0.3 },
      { nameIngredient: "перец черный молотый", amount: 0.2 },
      { nameIngredient: "лист лавровый", amount: 0.1 },
      { nameIngredient: "бактицид", amount: 0.5 },
      { nameIngredient: "черева свиная", amount: 16.7 },
      { nameIngredient: "пакет большой", amount: 23 },
    ],
  },
  {
    name: "Колбаса вареная К чаю любимая 2 с.",
    id: 45,
    outputValue: 130.0,
    ingredientsPrimary: [
      { nameIngredient: "мясо свиных голов", amount: 97.0 },
      { nameIngredient: "мука 1 сорт", amount: 3.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 1.2 },
      { nameIngredient: "пнс", amount: 1.0 },
      { nameIngredient: "промикс 400С", amount: 1.8 },
      { nameIngredient: "смесь сосисочная", amount: 1.2 },
      { nameIngredient: "черева говяжья", amount: 10.4 },
      { nameIngredient: "шпагат", amount: 0.26 },
    ],
  },
  {
    name: "Колбаса вареная Славянская новая 2с.",
    id: 46,
    outputValue: 135.0,
    ingredientsPrimary: [
      { nameIngredient: "говядина 2 сорта", amount: 45.0 },
      { nameIngredient: "шпик", amount: 18.0 },
      { nameIngredient: "мясо свиных голов", amount: 31.0 },
      { nameIngredient: "сухое молоко", amount: 1.0 },
      { nameIngredient: "мука 1 сорт", amount: 5.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 1.2 },
      { nameIngredient: "пнс", amount: 1.3 },
      { nameIngredient: "биямикс докторская", amount: 2.3 },
      { nameIngredient: "мусалонг", amount: 0.5 },
      { nameIngredient: "черева говяжья", amount: 10.8 },
      { nameIngredient: "шпагат", amount: 0.27 },
    ],
  },
  {
    name: "Шпикачки Русские новые 1 сорта",
    id: 47,
    outputValue: 145.0,
    ingredientsPrimary: [
      { nameIngredient: "говядина 2 сорта", amount: 40.0 },
      { nameIngredient: "свинина полужирная", amount: 20.0 },
      { nameIngredient: "м/о говяжья жилованная", amount: 10.0 },
      { nameIngredient: "шпик", amount: 25.0 },
      { nameIngredient: "меланж яичный сухой", amount: 0.822 },
      { nameIngredient: "сухое молоко", amount: 2.0 },
      { nameIngredient: "вода", amount: 2.178 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 1.0 },
      { nameIngredient: "пнс", amount: 1.0 },
      { nameIngredient: "тарома стаб 11", amount: 1.0 },
      { nameIngredient: "тарома докторская", amount: 1.2 },
      { nameIngredient: "проаром премьера", amount: 0.3 },
      { nameIngredient: "черева говяжья", amount: 11.6 },
      { nameIngredient: "шпагат", amount: 0.29 },
    ],
  },
  {
    name: 'Колбаса ливерная вареная "Смачная"',
    id: 48,
    outputValue: 125.0,
    ingredientsPrimary: [
      { nameIngredient: "соединительная ткань вареная", amount: 70.0 },
      { nameIngredient: "субпродукты второй категории вар.", amount: 30.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 2.2 },
      { nameIngredient: "аромикс 22", amount: 0.6 },
      { nameIngredient: "черева говяжья", amount: 10.0 },
      { nameIngredient: "шпагат", amount: 0.125 },
    ],
  },
  {
    name: 'Колбаса кровяная вареная "Селянская"',
    id: 49,
    outputValue: 130.0,
    ingredientsPrimary: [
      { nameIngredient: "шкурка вареная", amount: 30.0 },
      { nameIngredient: "крупа гречневая", amount: 6.7 },
      { nameIngredient: "кровь пищевая", amount: 40.0 },
      { nameIngredient: "шпик", amount: 10.0 },
      { nameIngredient: "вода", amount: 13.3 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 0.5 },
      { nameIngredient: "пнс", amount: 1.0 },
      { nameIngredient: "кашанка", amount: 0.8 },
      { nameIngredient: "мит фреш", amount: 0.3 },
      { nameIngredient: "черева говяжья", amount: 10.4 },
      { nameIngredient: "шпагат", amount: 0.13 },
    ],
  },
  {
    name: 'Колбасное кулинарное изделие "Колбаса от шефа"',
    id: 50,
    outputValue: 94.0,
    ingredientsPrimary: [
      { nameIngredient: "сердце+печень", amount: 67.0 },
      { nameIngredient: "шпик", amount: 27.0 },
      { nameIngredient: "меланж яичный сухой", amount: 1.0 },
      { nameIngredient: "крупа манная", amount: 2.0 },
      { nameIngredient: "лук жареный", amount: 3.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 1.0 },
      { nameIngredient: "перец черный молотый", amount: 0.4 },
      { nameIngredient: "кориандр молотый", amount: 0.4 },
      { nameIngredient: "семена горчицы", amount: 0.4 },
      { nameIngredient: "бактицид", amount: 0.5 },
      { nameIngredient: "эком рт", amount: 0.6 },
      { nameIngredient: "клетчатка растительная Биоцель", amount: 2.0 },
      { nameIngredient: "черева свиная", amount: 13.6 },
      { nameIngredient: "пакет вакуумный", amount: 188 },
    ],
  },
  {
    name: "Колбаса в/к Ветчинная 1с.",
    id: 51,
    outputValue: 115.0,
    ingredientsPrimary: [
      { nameIngredient: "свинина жирная", amount: 65.0 },
      { nameIngredient: "говядина односортная", amount: 33.0 },
      { nameIngredient: "крахмал", amount: 2.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 0.9 },
      { nameIngredient: "пнс", amount: 1.4 },
      { nameIngredient: "ветчинная краковская комби", amount: 0.9 },
      { nameIngredient: "инъекта", amount: 1.0 },
      { nameIngredient: "чесночный порошок", amount: 0.066 },
      { nameIngredient: "коллаген д55", amount: 80.5 },
      { nameIngredient: "шпагат", amount: 0.035 },
    ],
  },
  {
    name: "Колбаса п/к Киевская б/с",
    id: 52,
    outputValue: 95.0,
    ingredientsPrimary: [
      { nameIngredient: "свинина полужирная", amount: 100.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 1.0 },
      { nameIngredient: "пнс", amount: 1.4 },
      { nameIngredient: "краковское соло", amount: 0.5 },
      { nameIngredient: "перец черный молотый", amount: 0.2 },
      { nameIngredient: "чесночный порошок", amount: 0.066 },
      { nameIngredient: "черева свиная", amount: 16.1 },
      { nameIngredient: "шпагат", amount: 0.238 },
      { nameIngredient: "семена горчицы", amount: 0.15 },
    ],
  },
  {
    name: "Колбаса п/к Варшавская б/с",
    id: 53,
    outputValue: 90.0,
    ingredientsPrimary: [
      { nameIngredient: "говядина 2 сорта", amount: 30.0 },
      { nameIngredient: "свинина полужирная", amount: 40.0 },
      { nameIngredient: "шпик", amount: 30.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 1.0 },
      { nameIngredient: "пнс", amount: 1.0 },
      { nameIngredient: "краковская вареная", amount: 0.8 },
      { nameIngredient: "черева свиная", amount: 15.2 },
      { nameIngredient: "шпагат", amount: 0.225 },
    ],
  },
  {
    name: "Колбаса п/к Домашняя б/с",
    id: 54,
    outputValue: 95.0,
    ingredientsPrimary: [
      { nameIngredient: "свинина полужирная", amount: 75.0 },
      { nameIngredient: "говядина 2 сорта", amount: 25.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 1.0 },
      { nameIngredient: "пнс", amount: 1.4 },
      { nameIngredient: "краковское соло", amount: 0.5 },
      { nameIngredient: "перец черный молотый", amount: 0.2 },
      { nameIngredient: "чесночный порошок", amount: 0.066 },
      { nameIngredient: "черева говяжья", amount: 9.1 },
      { nameIngredient: "шпагат", amount: 0.238 },
    ],
  },
  {
    name: "Продукт к/в Любимый",
    id: 55,
    outputValue: 101.0,
    ingredientsPrimary: [
      { nameIngredient: "шейная часть (свинина полужирная)", amount: 100.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 0.4 },
      { nameIngredient: "пнс", amount: 2.0 },
      { nameIngredient: "хам брайн", amount: 2.25 },
      { nameIngredient: "актив фреш", amount: 0.5 },
      { nameIngredient: "пакет большой", amount: 10 },
      { nameIngredient: "пакет вакуумный", amount: 337 },
    ],
  },
  {
    name: "Продукт к/в Славянский",
    id: 56,
    outputValue: 102.0,
    ingredientsPrimary: [
      { nameIngredient: "спинно-поясничная часть (свинина нежирная)", amount: 100.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 0.4 },
      { nameIngredient: "пнс", amount: 2.0 },
      { nameIngredient: "хам брайн", amount: 2.25 },
      { nameIngredient: "актив фреш", amount: 0.5 },
      { nameIngredient: "пакет большой", amount: 10 },
      { nameIngredient: "пакет вакуумный", amount: 408 },
    ],
  },
  {
    name: "Продукт к/в Княжеский",
    id: 57,
    outputValue: 101.0,
    ingredientsPrimary: [
      { nameIngredient: "тазобедренная часть (свинина нежирная)", amount: 100.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 0.4 },
      { nameIngredient: "пнс", amount: 2.0 },
      { nameIngredient: "хам брайн", amount: 2.25 },
      { nameIngredient: "актив фреш", amount: 0.5 },
      { nameIngredient: "пакет большой", amount: 10 },
      { nameIngredient: "пакет вакуумный", amount: 337 },
    ],
  },
  {
    name: "Продукт к/в Домашний",
    id: 58,
    outputValue: 101.0,
    ingredientsPrimary: [
      { nameIngredient: "лопаточная часть (свинина нежирная)", amount: 100.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 0.4 },
      { nameIngredient: "пнс", amount: 2.0 },
      { nameIngredient: "хам брайн", amount: 2.25 },
      { nameIngredient: "актив фреш", amount: 0.5 },
      { nameIngredient: "пакет большой", amount: 10 },
      { nameIngredient: "пакет вакуумный", amount: 337 },
    ],
  },
  {
    name: "Продукт к/в Закуска домашняя",
    id: 59,
    outputValue: 103.0,
    ingredientsPrimary: [
      { nameIngredient: "грудореберная часть свиная без ребер", amount: 100.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 1.7 },
      { nameIngredient: "пнс", amount: 0.8 },
      { nameIngredient: "хам брайн", amount: 2.1 },
      { nameIngredient: "актив фреш", amount: 0.25 },
      { nameIngredient: "пакет большой", amount: 10 },
      { nameIngredient: "пакет вакуумный", amount: 343 },
    ],
  },
  {
    name: "Продукт к/в Ребрышки любимые",
    id: 60,
    outputValue: 80.0,
    ingredientsPrimary: [
      { nameIngredient: "грудореберная часть свиная с ребрами 50/50", amount: 100.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 0.4 },
      { nameIngredient: "пнс", amount: 2.0 },
      { nameIngredient: "хам брайн", amount: 2.25 },
      { nameIngredient: "актив фреш", amount: 0.5 },
      { nameIngredient: "пакет большой", amount: 8 },
    ],
  },
  {
    name: "Колбаса в/к Салями премиум в/с",
    id: 61,
    outputValue: 100.0,
    ingredientsPrimary: [
      { nameIngredient: "м/о говяжья жилованная", amount: 40.0 },
      { nameIngredient: "свинина полужирная", amount: 20.0 },
      { nameIngredient: "мясо птицы кусковое", amount: 20.0 },
      { nameIngredient: "шпик", amount: 10.0 },
      { nameIngredient: "шкурка свиная", amount: 10.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "пнс", amount: 1.8 },
      { nameIngredient: "кутроцит", amount: 1.0 },
      { nameIngredient: "соваром чоризо", amount: 1.2 },
      { nameIngredient: "каркадогель", amount: 0.25 },
      { nameIngredient: "колор КП", amount: 0.066 },
      { nameIngredient: "фиброуз д45", amount: 105.6 },
      { nameIngredient: "скрепки", amount: 446 },
      { nameIngredient: "петли", amount: 223 },
      { nameIngredient: "пакет вакуумный", amount: 333 },
    ],
  },
  {
    name: 'Соленый продукт из свинины "Солонина-буженина"',
    id: 62,
    outputValue: 90.0,
    ingredientsPrimary: [
      { nameIngredient: "свинина нежирная", amount: 100.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 5.0 },
      { nameIngredient: "про смак", amount: 1.5 },
      { nameIngredient: "приправа Барбекю обсыпка декор", amount: 1.5 },
      { nameIngredient: "пакет вакуумный", amount: 200 },
    ],
  },
  {
    name: 'Соленый продукт из свинины "Солонина-ковалочек"',
    id: 63,
    outputValue: 90.0,
    ingredientsPrimary: [
      { nameIngredient: "свинина нежирная", amount: 100.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 5.0 },
      { nameIngredient: "про смак", amount: 1.5 },
      { nameIngredient: "приправа Карри гриль", amount: 1.5 },
      { nameIngredient: "пакет вакуумный", amount: 200 },
    ],
  },
  {
    name: "Рулет к/в Филейный",
    id: 64,
    outputValue: 128.0,
    ingredientsPrimary: [
      { nameIngredient: "мясо птицы кусковое", amount: 65.0 },
      { nameIngredient: "свинина полужирная", amount: 32.0 },
      { nameIngredient: "крахмал", amount: 3.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 1.65 },
      { nameIngredient: "пнс", amount: 0.58 },
      { nameIngredient: "комплект ветчинный", amount: 3.1 },
      { nameIngredient: "аромат хам", amount: 0.2 },
      { nameIngredient: "хаммикс 20", amount: 1.1 },
      { nameIngredient: "фреш", amount: 0.25 },
    ],
  },
  {
    name: "Кулинарное изделие Флячки по-деревенски",
    id: 65,
    outputValue: 58.0,
    ingredientsPrimary: [
      { nameIngredient: "рубец зачищенный", amount: 100.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 0.1 },
      { nameIngredient: "бактицид", amount: 0.3 },
      { nameIngredient: "приправа Деревенская", amount: 0.3 },
      { nameIngredient: "пакет большой", amount: 50 },
    ],
  },
  {
    name: "Колбаса с/к Киндюк в/с",
    id: 66,
    outputValue: 60.0,
    ingredientsPrimary: [
      { nameIngredient: "свинина полужирная", amount: 50.0 },
      { nameIngredient: "говядина односортная", amount: 30.0 },
      { nameIngredient: "шпик", amount: 20.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "пнс", amount: 2.6 },
      { nameIngredient: "соваром киндюк", amount: 1.5 },
      { nameIngredient: "совмикс GP", amount: 0.4 },
      { nameIngredient: "чесночный порошок", amount: 0.1 },
      { nameIngredient: "черева свиная", amount: 11.3 },
      { nameIngredient: "шпагат", amount: 0.18 },
      { nameIngredient: "пакет вакуумный", amount: 240 },
    ],
  },
  {
    name: "Колбаса с/к Фирменная в/с",
    id: 67,
    outputValue: 70.0,
    ingredientsPrimary: [
      { nameIngredient: "свинина полужирная", amount: 80.0 },
      { nameIngredient: "шпик", amount: 20.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "пнс", amount: 2.6 },
      { nameIngredient: "соваром традиционная", amount: 1.5 },
      { nameIngredient: "совмикс GP", amount: 0.4 },
      { nameIngredient: "чесночный порошок", amount: 0.1 },
      { nameIngredient: "черева свиная", amount: 13.2 },
      { nameIngredient: "шпагат", amount: 0.21 },
      { nameIngredient: "пакет вакуумный", amount: 280 },
    ],
  },
  {
    name: "Колбаса с/к Для свояка в/с",
    id: 68,
    outputValue: 70.0,
    ingredientsPrimary: [
      { nameIngredient: "свинина полужирная", amount: 80.0 },
      { nameIngredient: "шпик", amount: 20.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "пнс", amount: 2.6 },
      { nameIngredient: "соваром ароматная", amount: 1.3 },
      { nameIngredient: "совмикс GP", amount: 0.4 },
      { nameIngredient: "чесночный порошок", amount: 0.1 },
      { nameIngredient: "черева свиная", amount: 13.2 },
      { nameIngredient: "шпагат", amount: 0.21 },
      { nameIngredient: "пакет вакуумный", amount: 280 },
    ],
  },
  {
    name: "Колбаса с/к Для охотника в/с",
    id: 69,
    outputValue: 52.0,
    ingredientsPrimary: [
      { nameIngredient: "свинина полужирная", amount: 100.0 },
    ],
    ingredientsSecondary: [
      { nameIngredient: "соль", amount: 0.3 },
      { nameIngredient: "пнс", amount: 1.8 },
      { nameIngredient: "совмикс GP", amount: 0.5 },
      { nameIngredient: "соваром чоризо", amount: 0.5 },
      { nameIngredient: "соваром ведзонка", amount: 0.5 },
      { nameIngredient: "натурин д20", amount: 87.2 },
      { nameIngredient: "пакет вакуумный", amount: 11 },
    ],
  },
];
