export let startValue = 100;

export let products = [
    {
        name: 'Колбаса п/к Застольная б/с',
        id: 1,
        outputValue : 95.0,
        ingredientsPrimary: [
            { nameIngredient:'мясо гов. гол.',
              amount:52.0},
            { nameIngredient:'шпик',
              amount:20.0},
            { nameIngredient:'изолят соевого белка',
              amount:7.0},
            { nameIngredient:'вода',
              amount:21.0},
        ],
        ingredientsSecondary: [
            { nameIngredient:'соль',
              amount:0.700},
            { nameIngredient:'нпс',
              amount:1.600},
            { nameIngredient:'биями комби 37',
              amount:1.700},
            { nameIngredient:'донор 16',
              amount:0.200},
            { nameIngredient:'чесночный порошок',
              amount:0.100},
            { nameIngredient:'черева гов.',
              amount:9.1},
            { nameIngredient:'шпагат',
              amount:0.238},
        ]
    },
    {
        name: 'Шашлык Южный в маринаде',
        id: 2,
        outputValue : 140.0,
        ingredientsPrimary: [
            { nameIngredient:'свинина не/ж',
              amount:100.0},
        ],
        ingredientsSecondary: [
            { nameIngredient:'соль',
              amount:0.800},
            { nameIngredient:'про ветчина ЗОА',
              amount:1.200},
            { nameIngredient:'растительное масло',
              amount:7.000},
            { nameIngredient:'маринад пирожка',
              amount:3.000},
            { nameIngredient:'пакет',
              amount:28},
        ]
    },
    {
        name: 'Колбаса п/к Фермерская с грибочками и лучком в/с',
        id: 3,
        outputValue : 110.0,
        ingredientsPrimary: [
            { nameIngredient:'свин. п/ж',
              amount:75.0},
            { nameIngredient:'гов. однос.',
              amount:20.0},
            { nameIngredient:'крахмал',
              amount:5.0},
        ],
        ingredientsSecondary: [
            { nameIngredient:'нпс',
              amount:1.200},
            { nameIngredient:'совмикс Ф500',
              amount:1.500},
            { nameIngredient:'соваром грибной',
              amount:1.350},
            { nameIngredient:'комбивит',
              amount:0.400},
            { nameIngredient:'совицель',
              amount:0.300},
            { nameIngredient:'черева говяжья',
              amount:105.6},
            { nameIngredient:'шпагат',
              amount:0.275},
            { nameIngredient:'пакет вак.',
              amount:275},
            { nameIngredient:'соваром цебуля',
              amount:0.300},
        ]
    },
]
